development:
  adapter: postgresql
  encoding: utf8
  database: development
  pool: 5
  timeout: 5000
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: teste
  port: 5432
  pool: 5
  timeout: 5000

production:
  adpter: postgresql
  encoding: utf8
  database: production
  pool: 5
  timeout: 5000
  port: 5432
